example/config/routes.rb
Example::Application.routes.draw do
  github_authenticate do
    get '/orgs' => 'organizations#index', as: :orgs
    get '/profile' => 'users#show', as: :profile
  end

  github_authenticate(team: lambda { |req| req.params[:id] }) do
    get '/teams/:id' => 'teams#show', as: :team
  end

  github_authenticate(org: lambda { |req| req.params[:id] }) do
    get '/orgs/:id' => 'organizations#show', as: :org
  end

  get '/login'  => 'sessions#create', as: :login
  get '/logout' => 'sessions#destroy', as: :logout

  resources :users

  root to: 'home#show'

  match '*all' => 'application#not_found', via: :all
end

example/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def not_found
    render status: 404
  end
end

example/app/controllers/home_controller.rb
class HomeController < ApplicationController
end

example/app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def index
    @orgs = github_user.api.organizations
  end

  def show
    @org = github_user.api.organization(params[:id])
    @members = github_user.api.organization_members(params[:id])
    @repos = github_user.api.organization_repositories(params[:id])
    @teams = github_user.api.organization_teams(params[:id])
  end
end

example/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    github_authenticate!
    redirect_to root_url
  end

  def destroy
    github_logout
    redirect_to root_url
  end
end

example/app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def show
    @team = github_user.api.team(params[:id])
    @repos = github_user.api.team_repositories(params[:id])
    @members = github_user.api.team_members(params[:id])
  end
end

example/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = github_user.api.user(params[:id])
    @repos = github_user.api.repos(params[:id])
  end
end

example/app/views/application/not_found.html.erb
<h2>404</h2>

<p>Hmm..., looks like there's nothing here for you!</p>

example/app/views/home/show.html.erb
<h2>Welcome</h2>

<p>Try accessing an organization through urls like <a href='/orgs/rails'>/orgs/rails</a>. If you're not a member of that organization, you'll see a 404. Same for teams.</p>

example/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Example App</title>
    <style type="text/css">
      html {
        font: 1em / 1.4 'Helvetica Neue', Helvetica, Arial, sans-serif;
        background: #efefef;
      }

      h1 {
        font-size: 3em;
        text-align: center;
      }

      hr {
        border-top: 1px solid #333;
      }

      nav {
        text-align: center;
      }

      nav li, nav ul {
        display: inline;
        list-style: none;
        padding: 0;
      }

      nav li::before {
        content: ' | ';
        padding: 0 0.5em;
      }

      nav li:first-child::before {
        content: none;
      }

      .container {
        width: 90%;
        max-width: 54em;
        background: white;
        padding: 1em 2em;
        margin: 1em auto;
      }

      img {
        vertical-align: middle;
      }
    </style>
  </head>
  <body>

    <h1>Example App</h1>

    <nav>
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Organizations', orgs_path %></li>
        <li><%= link_to 'Profile', profile_path %></li>
        <%- if github_authenticated? %>
          <li><%= link_to "Logout (#{github_user.name})", logout_path %></li>
        <%- else -%>
          <li><%= link_to 'Login', login_path %></li>
        <%- end -%>
      </ul>
    </nav>

    <div class='container'>
      <%= yield %>
    </div>

  </body>
</html>

example/app/views/organizations/index.html.erb
<h2>Your Organizations</h2>

<%- if @orgs.empty? -%>
<p>Looks like you are not a member of any organization :-(</p>
<%- else -%>
<ul>
  <%- @orgs.each do |org| -%>
  <li>
    <%= image_tag org.rels[:avatar].href, width: 25, height: 25 %>
    <%= link_to org.login, org_path(org.login) %>
  </li>
  <%- end -%>
</ul>
<%- end -%>

example/app/views/organizations/show.html.erb
<h2>
  <%= image_tag @org.rels[:avatar].href, width: 50, height: 50 %>
  <%= @org.login %>
</h2>

<h3>Repositories</h3>
<%- if @repos.empty? -%>
<p>Looks like there are no repos in this organization :-(</p>
<%- else -%>
<dl>
  <%- @repos.each do |repo| -%>
  <dt><%= link_to repo.name, repo.rels[:html].href %></dt>
  <dd><%= repo.description %></dd>
  <%- end -%>
</dl>
<%- end -%>

<h3>Teams</h3>

<%- if @teams.empty? -%>
<p>Looks like there are no teams :-(</p>
<%- else -%>
<ul>
  <%- @teams.each do |team| -%>
  <li><%= link_to team.name, team_path(team.id) %></li>
  <%- end -%>
</ul>
<%- end -%>

<h3>Members</h3>
<ul>
  <%- @members.each do |member| -%>
  <li>
    <%= image_tag member.rels[:avatar].href, width: 25, height: 25 %>
    <%= link_to member.login, user_path(member.login) %>
  </li>
  <%- end -%>
</ul>

example/app/views/users/show.html.erb
<h2>
  <%= image_tag @user.rels[:avatar].href, width: 50, height: 50 %>
  <%= @user.login %>
  <%- if @user.name.present? %>
  (<%= @user.name %>)
  <%- end -%>
</h2>

<dl>
  <dt>Company:</dt>
  <dd><%= @user.company %></dd>
  <dt>Website:</dt>
  <dd><%= @user.blog %><dd>
  <dt>Bio:</dt>
  <dd><%= @user.bio %><dd>
</dl>

<h3>Repositories</h3>
<%- if @repos.empty? -%>
<p>Looks like this user has no repos :-(</p>
<%- else -%>
<dl>
  <%- @repos.each do |repo| -%>
  <dt><%= link_to repo.name, repo.rels[:html].href %></dt>
  <dd><%= repo.description %></dd>
  <%- end -%>
</dl>
<%- end -%>